# workflow
# should have name
name: Hello
# on tells when the workflow should run 
on:    
 workflow_dispatch:

#job tells what the workflow should do,there cab be more than one jobs.
#jobs is an object so needs indentation

jobs:
#1st job (give indentation)
  say-hello: 
  #creates an ephermal container with ubuntu running
   runs-on: ubuntu-latest
   #that ephermal container will have steps to execute,hence name thoses steps and use run.
   steps:
     - name: Say hello to everyone
       run: echo "Hello Dosto"
       
# Steps 
#should be inside the job

# Actions
#should be inside the steps
